title: "Phaneendra Siddana's Portfolio"
description: "Experienced Full Stack Java Developer specializing in scalable solutions"
theme: jekyll-theme-minimal
baseurl: ""
url: "https://phaneendras9.github.io"
email: "siddanaphaneendra9@gmail.com"
social_links:
  linkedin: "https://www.linkedin.com/in/sphanee/"
  github: "https://github.com/phaneendras9"

# Additional configuration
author: "Phaneendra Siddana"
